#include<bits/stdc++.h>

using namespace std;
struct node {
	unsigned long long x, y, p, t;
};
vector<struct node> seq;

class BitPacker {
	private:
		std::vector<uint8_t> data;

		uint64_t buffer = 0;
		int bits = 0;

	public:

		void pack(uint64_t value, int bit_count) {

			while (bit_count > 0) {

				int free_bits = 64 - bits;
				int take = min(bit_count, free_bits);

				uint64_t mask;

				if (take == 64)
					mask = UINT64_MAX;
				else
					mask = (1ULL << take) - 1;

				value &= mask;

				buffer |= value << bits;
				bits += take;

				value >>= take;
				bit_count -= take;

				while (bits >= 8) {

					data.push_back(
					    static_cast<uint8_t>(buffer & 0xFF)
					);

					buffer >>= 8;
					bits -= 8;
				}
			}
		}

		void flush() {

			if (bits > 0) {

				data.push_back(
				    static_cast<uint8_t>(buffer & 0xFF)
				);

				buffer = 0;
				bits = 0;
			}
		}

		const std::vector<uint8_t>& get_data() const {
			return data;
		}
};

int main() {
	FILE *fp;
	fp = fopen("result/all_events.txt", "r");
	if (fp == NULL) {
		printf("Cannot open all_events.txt\n");
		return -1;
	}
	unsigned int magic;
	unsigned int version;
	unsigned long long start_time;
	short int max_time_diff;
	short int width;
	short int height;
	uint8_t TimestampType;// 0 for uint32, 1 for uint64
	/*data format:
				1.delta t, (length in bits) depend on max_time_diff.
				2.p, 1 bit
				3.dots,  32 - __builtin_clz(width * height);
					generated by x*height+y
	*/
	magic = 20260916;
	version = 1;

	struct node temp;
	while (fscanf(fp, "%llu%llu%llu%llu", &temp.x, &temp.y, &temp.p, &temp.t) == 4) {
		seq.push_back(temp);
	}
	fclose(fp);

	start_time = seq[0].t;
	int len = seq.size();

	for (int i = 1; i < len; i++) {
		if (seq[i].t < seq[i - 1].t) {
			printf("INPUT ERROR: timestamp not sorted\n");
			return -1;
		}
	}

	unsigned long long delta_t = 0;
	for (int i = 1; i < len; i++) {
		delta_t = max(delta_t, seq[i].t - seq[i - 1].t);
	}

	if (delta_t == 0) {
		printf("INPUT ERROR\n");
		return -1;
	}
	max_time_diff = 32 - __builtin_clz(delta_t);

	//input width,height,TimestampType
	width = 1280;
	height = 720;
	TimestampType = 0;

	ofstream OutFile("result/events.dat", ios::out | ios::binary);

	OutFile.write((char *)&magic, sizeof(magic));
	OutFile.write((char *)&version, sizeof(version));
	OutFile.write((char *)&start_time, sizeof(start_time));
	OutFile.write((char *)&max_time_diff, sizeof(max_time_diff));
	OutFile.write((char *)&width, sizeof(width));
	OutFile.write((char *)&height, sizeof(height));
	OutFile.write((char *)&TimestampType, sizeof(TimestampType));

	BitPacker packer;
	unsigned int last_time_stamp = start_time;
	unsigned int dot_len = 32 - __builtin_clz(width * height);
	for (int i = 0; i < len; i++) {
		packer.pack(seq[i].t - last_time_stamp, max_time_diff);
		packer.pack(seq[i].x * height + seq[i].y, dot_len);
		packer.pack(seq[i].p, 1);
		last_time_stamp = seq[i].t;
	}
	packer.flush();

	const auto& data = packer.get_data();

	for (uint8_t byte : data) {

		OutFile.write(
		    reinterpret_cast<char*>(&byte),
		    sizeof(byte)
		);
	}
	cout << '\n' << '\n';
	cout << "------Compression Information------" << '\n';
	cout << "event_bits = " << max_time_diff + 1 + dot_len << '\n';
	cout << "Finished!" << '\n';
	cout << "-----------------------------------" << '\n';
	return 0;
}
